// Generated by typings
// Source: https://raw.githubusercontent.com/dojo/typings/004fc065b3b24412c9b6575cdc06545964c370b5/custom/dojo2-extras/maquette.d.ts
declare module 'maquette/maquette' {
	export * from 'maquette';
}