// Generated by typings
// Source: https://raw.githubusercontent.com/dojo/typings/004fc065b3b24412c9b6575cdc06545964c370b5/custom/dojo2-extras/rxjs.d.ts
declare module 'rxjs/Rx' {
	export * from '@reactivex/RxJS';
}

declare module 'rxjs/Observable' {
	import * as Observable from '@reactivex/RxJS/dist/cjs/Observable';
	export = Observable;
}

declare module 'rxjs/Observer' {
	import * as Observer from '@reactivex/RxJS/dist/cjs/Observer';
	export = Observer;
}